CREATE TABLE [dbo].[BTR_Role]
(
	RoleId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Role_RoleId DEFAULT(''),
	RoleName VARCHAR(30) NOT NULL CONSTRAINT DF_BTR_Role_RoleName DEFAULT(''),

	CONSTRAINT PK_BTR_Role PRIMARY KEY CLUSTERED(RoleId)
)