CREATE TABLE [dbo].[BTR_DocAction]
(
	DocId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_DocAction_DocId DEFAULT(''),
	ActionDate DATETIME NOT NULL CONSTRAINT DF_BTR_DocAction_ActionDate DEFAULT('3000-01-01'),
	[Action] VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_DocAction_Action DEFAULT(''),

	CONSTRAINT PK_BTR_DocAction PRIMARY KEY CLUSTERED(DocId, ActionDate)
)
