CREATE TABLE [dbo].[BTR_DocAction]
(
	DocId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_DocAction_DocId DEFAULT(''),
	ActionDate DATETIME NOT NULL CONSTRAINT DF_BTR_DocAction_ActionDate DEFAULT('3000-01-01'),
	[Action] VARCHAR(256) NOT NULL CONSTRAINT DF_BTR_DocAction_Action DEFAULT(''),
)
GO

CREATE CLUSTERED INDEX CX_BTR_DocAction
	ON BTR_DocAction (DocId, ActionDate)
	WITH(FILLFACTOR=80)
GO
