CREATE TABLE BTR_ParamNo(
    Prefix VARCHAR(10) NOT NULL CONSTRAINT BTR_ParamNo_Prefix DEFAULT(''),
    HexVal VARCHAR(20) NOT NULL CONSTRAINT BTR_ParamNo_HexVal DEFAULT(''),
    
    CONSTRAINT PK_BTR_ParamNo PRIMARY KEY CLUSTERED(Prefix)
)