CREATE TABLE [dbo].[BTR_RoleMenu]
(
	RoleId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_RoleMenu_RoleId DEFAULT(''),
	MenuId VARCHAR(4) NOT NULL CONSTRAINT DF_BTR_RoleMenu_MenuId DEFAULT(''),

	CONSTRAINT PK_BTR_RoleMenu PRIMARY KEY CLUSTERED(RoleId, MenuId)
)