CREATE TABLE [dbo].[BTR_Menu]
(
	MenuId VARCHAR(4) NOT NULL CONSTRAINT DF_BTR_Menu_MenuId DEFAULT(''),
	MenuName VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_Menu_MenuName DEFAULT(''),
	Caption VARCHAR(100) NOT NULL CONSTRAINT DF_BTR_Menu_Caption DEFAULT(''),

	CONSTRAINT PK_BTR_Menu PRIMARY KEY CLUSTERED(MenuId)
)

GO
