CREATE TABLE [dbo].[BTR_User]
(
	UserId VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_User_UserId DEFAULT(''),
	UserName VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_User_UserName DEFAULT(''),
	Password VARCHAR(64) NOT NULL CONSTRAINT DF_BTR_User_Password DEFAULT(''),
	Prefix VARCHAR(2) NOT NULL CONSTRAINT DF_BTR_User_Prefix DEFAULT(''),
	RoleId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_User_Role DEFAULT(''),

	CONSTRAINT PK_BTR_User PRIMARY KEY CLUSTERED(UserId)
)
