CREATE TABLE BTR_Brg(
    BrgId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Brg_BrgId DEFAULT(''),
    BrgName VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_Brg_BrgName DEFAULT(''),
    IsAktif VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Brg_IsAktif DEFAULT(''),
    SupplierId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Brg_SupplierId DEFAULT(''),
    KategoriId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Brg_KategoriId DEFAULT(''),
    Hpp VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Brg_Hpp DEFAULT(''),
    HppTimestamp VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Brg_HppTimestamp DEFAULT(''),
    
    CONSTRAINT PK_BTR_Brg PRIMARY KEY CLUSTERED (BrgId)
)