CREATE TABLE BTR_Brg(
    BrgId VARCHAR(6) NOT NULL CONSTRAINT DF_BTR_Brg_BrgId DEFAULT(''),
    BrgName VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_Brg_BrgName DEFAULT(''),
    BrgCode VARCHAR(10) NOT NULL CONSTRAINT DF_BTR_Brg_BrgCode DEFAULT(''),
    IsAktif BIT NOT NULL CONSTRAINT DF_BTR_Brg_IsAktif DEFAULT(''),

    SupplierId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Brg_SupplierId DEFAULT(''),
    JenisBrgId VARCHAR(3) NOT NULL CONSTRAINT DF_BTR_Brg_JenisBrgId DEFAULT(''), 
    KategoriId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Brg_KategoriId DEFAULT(''),

    Hpp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Brg_Hpp DEFAULT(''),
    HppTimestamp DATETIME NOT NULL CONSTRAINT DF_BTR_Brg_HppTimestamp DEFAULT(''),
    
    CONSTRAINT PK_BTR_Brg PRIMARY KEY CLUSTERED (BrgId)
)