CREATE TABLE [dbo].[BTR_Kategori]
(
	KategoriId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Kategori_KategoriId DEFAULT(''),
	KategoriName VARCHAR(30) NOT NULL CONSTRAINT DF_BTR_Kategori_KategoriName DEFAULT(''),
	Code VARCHAR(15) NOT NULL CONSTRAINT DF_BTR_Kategori_Code DEFAULT(''),
	SupplierId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Kategori_SupplierId DEFAULT(''),

	CONSTRAINT PK_BTR_Kategori PRIMARY KEY CLUSTERED(KategoriId)
)
