
INSERT INTO Menus (MenuId, MenuName, Caption) VALUES
('ST1', 'ST1FakturMenu', 'ST1-Faktur'),
('ST2', 'ST2ControlFakturMenu', 'ST2-Control Faktur'),
('ST3', 'ST3SalesReplacementMenu', 'ST3-Sales Replacement'),
('ST4', 'ST4SalesOrderMenu', 'ST4-Sales Order'),
('SM1', 'SM1CustomerMenu', 'SM1-Customer'),
('SM2', 'SM2SalesPersonMenu', 'SM2-Sales Person'),
('SM3', 'SM3WilayahMenu', 'SM3-Wilayah'),
('SM4', 'SM4RuteMenu', 'SM4-Rute'),
('SF1', 'SF1FakturInfoMenu', 'SF1-Info Faktur ...'),
('SF2', 'SF2FakturBrgInfoMenu', 'SF2-Info Faktur Barang ...'),
('SF3', 'SF3FakturPerSupplierInfoMenu', 'SF3-Info Faktur Per Supplier ...'),
('SF4', 'SF4FakturPerCustomerInfoMenu', 'SF4-Info Faktur Per Customer ...'),
('SF5', 'SF5FakturPajakInfoMenu', 'SF5-Info Faktur Pajak...'),
('SF6', 'SF6FakturCashInfoMenu', 'SF6-Info Faktur Cash ...'),
('SF7', 'SF7OmzetPerSupplierInfoMenu', 'SF7-Info Omzet Per Supplier ...'),
('SF8', 'SF8FakturPerDriverInfoMenu', 'SF8-Info Faktur Per Driver ...'),
('RO1', 'RO1CheckInListMenu', 'RO1-CheckIn List'),
('RO2', 'RO2SalesOmzetMenu', 'RO2-Sales Omzet'),
('RO3', 'RO3EffectiveCallMenu', 'RO3-Effective Call'),
('RO4', 'RO4CoordinateCoverageMenu', 'RO4-Coordinate Coverage'),
('PT1', 'PT1InvoiceMenu', 'PT1-Invoice'),
('PT2', 'PT2PostingStokMenu', 'PT2-Posting Stok'),
('PT3', 'PT3ReturBeliMenu', 'PT3-Retur Beli'),
('PF1', 'PF1InvoiceInfoMenu', 'PF1-Invoice'),
('PF2', 'PF2InvoiceBrgInfoMenu', 'PF2-Invoice Brg Info'),
('PF3', 'PF3InvoiceHarianInfoMenu', 'PF3-Invoice Harian'),
('PF4', 'PF4ReturBeliDetilMenu', 'PF4-Retur Beli Detil'),
('PM1', 'PM1SupplierMenu', 'PM1-Supplier'),
('IT1', 'IT1OpnameMenu', 'IT1-Opname'),
('IT3', 'IT3PackingMenu', 'IT3-Packing'),
('IT4', 'IT4MutasiMenu', 'IT4-Mutasi'),
('IT6', 'IT6AdjustmentMenu', 'IT6-Adjustment'),
('IF1', 'IF1StokBalanceMenu', 'IF1-Stok Balance'),
('IF2', 'IF2KartuStokMenu', 'IF2-Kartu Stok'),
('IF4', 'IF4StokPerSupplierMenu', 'IF4-Stok Supplier'),
('IF5', 'IF5StokPeriodikMenu', 'IF5-Stok Periodik'),
('IF6', 'IF6StokMutasiMenu', 'IF6-Mutasi Info'),
('IF7', 'IF7StokOpnameMenu', 'IF7-Stok Opname'),
('IF8', 'IF8KartuStokMenu', 'IF8-KartuStok Summary'),
('IM1', 'IM1BrgMenu', 'IM1-Barang'),
('IM2', 'IM2WarehouseMenu', 'IM2-Gudang'),
('IM3', 'IM3KategoriMenu', 'IM3-Kategori'),
('IM4', 'IM4DriverMenu', 'IM4-Driver'),
('FT2', 'FT2TagihanSalesMenu', 'FT2-Tagihan Sales'),
('FT4', 'FT4TandaTerimaMenu', 'FT4-Tanda Terima'),
('FT1', 'FT1LunasPiutangMenu', 'FT1-Lunas Piutang'),
('FT5', 'FT5PiutangTrackerMenu', 'FT5-Piutang Tracker'),
('FT3', 'FT3FpKeluaranMenu', 'FT3-FP Keluaran'),
('FF1', 'FF1PiutangSalesWilayahMenu', 'FF1-Piutang Sales'),
('FF2', 'FF2PenerimaanSalesMenu', 'FF2-Penerimaan Sales'),
('FF3', 'FF3FpKeluaranMenu', 'FF3-FP Keluaran'),
('FF4', 'FF4PelunasanInfoBMenu', 'FF4-Pelunasan Info'),
('RT1', 'RT1ReturJualMenu', 'RT1-Retur Jual'),
('RT2', 'RT2PostingReturMenu', 'RT2-Posting Retur'),
('RF1', 'RF1ReturJualInfoMenu', 'RF1-Info Retur'),
('RF2', 'RF2ReturBrgInfoMenu', 'RF2-Info Retr-Brg'),
('RF3', 'RF3ReturJualPerSupplierInfoMenu', 'RF3-Retur Per-Supplier'),
('XX1', 'XX1UserMenu', 'XX1-User'),
('XX2', 'XX2ParameterSistemMenu', 'XX2-Parameter Sistem'),
('XX3', 'XX3AboutMenu', 'XX3-About');