CREATE TABLE [dbo].[BTR_PiutangLunas]
(
	PiutangId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_PiutangLunas_PiutangId DEFAULT(''),
	NoUrut INT NOT NULL CONSTRAINT DF_BTR_PiutangLunas_NoUrut DEFAULT(0),
	LunasDate VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_PiutangLunas_LunasDate DEFAULT('3000-01-01'),
	Nilai DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_PiutangLunas_Nilai DEFAULT(0),
	JenisLunas INT NOT NULL CONSTRAINT DF_BTR_PiutangLunas_JenisLunas DEFAULT(0),

	CONSTRAINT PK_BTR_PiutangLunas PRIMARY KEY CLUSTERED(PiutangId, NoUrut)
)
