CREATE TABLE [dbo].[BTR_Piutang]
(
	PiutangId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_Piutang_PiutangId DEFAULT(''),
	PiutangDate DATETIME NOT NULL CONSTRAINT DF_BTR_Piutang_PiutangDate DEFAULT('3000-01-01'),
	DueDate DATETIME NOT NULL CONSTRAINT DF_BTR_Piutang_DueDate DEFAULT('3000-01-01'),
	CustomerId VARCHAR(6) NOT NULL CONSTRAINT DF_BTR_Piutang_CustomerId DEFAULT(''),
	Total DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Piutang_Total DEFAULT(0),
	Terbayar DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Piutang_Terbayar DEFAULT(0),
	Sisa DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Piutang_Sisa DEFAULT(0),

	CONSTRAINT PK_BTR_Piutang PRIMARY KEY CLUSTERED(PiutangId)
)
GO

CREATE INDEX IX_BTR_Piutang_PiutangDate 
	ON [dbo].[BTR_Piutang](PiutangDate, PiutangId)
	WITH(FILLFACTOR=95)
GO