CREATE TABLE [dbo].[BTR_ReturBeli]
(
	ReturBeliId VARCHAR(10) NOT NULL CONSTRAINT DF_BTR_ReturBeli_ReturBeliId DEFAULT(''),
	ReturBeliDate DATETIME NOT NULL CONSTRAINT DF_BTR_ReturBeli_ReturBeliDate DEFAULT('3000-01-01'),
	UserId VARCHAR(10) NOT NULL CONSTRAINT DF_BTR_ReturBeli_UserId DEFAULT(''),
	SupplierId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_ReturBeli_SupplierId DEFAULT(''),
	WarehouseId VARCHAR(3) NOT NULL CONSTRAINT DF_BTR_ReturBeli_WarehouseId DEFAULT(''),
	DiscountLain DECIMAL(18, 2) NOT NULL CONSTRAINT DF_BTR_ReturBeli_DiscountLain DEFAULT(0),
	BiayaLain DECIMAL(18, 2) NOT NULL CONSTRAINT DF_BTR_ReturBeli_BiayaLain DEFAULT(0),

	CONSTRAINT PK_BTR_ReturBeli PRIMARY KEY CLUSTERED (ReturBeliId ASC),
)
