CREATE TABLE BTR_ReturBeli
(
    ReturBeliId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_ReturBeli_ReturBeliId DEFAULT(''),    
    ReturBeliDate DATETIME NOT NULL CONSTRAINT DF_BTR_ReturBeli_ReturBeliDate DEFAULT('3000-01-01'), 
    ReturBeliCode VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_ReturBeli_ReturBeliCode DEFAULT(''), 

    SupplierId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_ReturBeli_SupplierId DEFAULT(''), 
    WarehouseId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_ReturBeli_WarehouseId DEFAULT(''), 

    NoFakturPajak VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_ReturBeli_NoFakturPajak DEFAULT(''), 
    Total DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturBeli_Total DEFAULT(0), 
    Disc DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturBeli_Discount DEFAULT(0),
    Dpp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturBeli_Dpp DEFAULT(0),
    Tax DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturBeli_Tax DEFAULT(0), 
    GrandTotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturBeli_GrandTotal DEFAULT(''),

    CreateTime DATETIME NOT NULL CONSTRAINT DF_BTR_ReturBeli_CreateTime DEFAULT('3000-01-01'),
    LastUpdate DATETIME NOT NULL CONSTRAINT DF_BTR_ReturBeli_LastUpdate DEFAULT('3000-01-01'),
    UserId VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_ReturBeli_UserId DEFAULT(''),

    VoidDate DATETIME NOT NULL CONSTRAINT DF_BTR_ReturBeli_VoidDate DEFAULT('3000-01-01'),
    UserIdVoid VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_ReturBeli_UserIdVoid DEFAULT(''),

    
    CONSTRAINT PK_BTR_ReturBeli PRIMARY KEY CLUSTERED (ReturBeliId)
)