CREATE TABLE BTR_Invoice
(
    InvoiceId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_Invoice_InvoiceId DEFAULT(''),    
    InvoiceDate DATETIME NOT NULL CONSTRAINT DF_BTR_Invoice_InvoiceDate DEFAULT('3000-01-01'), 
    InvoiceCode VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_Invoice_InvoiceCode DEFAULT(''), 

    SupplierId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Invoice_SupplierId DEFAULT(''), 
    WarehouseId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Invoice_WarehouseId DEFAULT(''), 

    NoFakturPajak VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_Invoice_NoFakturPajak DEFAULT(''), 
    DueDate DATETIME NOT NULL CONSTRAINT DF_BTR_Invoice_DueDate DEFAULT('3000-01-01'), 
    Total DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Invoice_Total DEFAULT(''), 
    Disc DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Invoice_Discount DEFAULT(''), 
    Tax DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Invoice_Tax DEFAULT(''), 
    GrandTotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Invoice_GrandTotal DEFAULT(''),

    CreateTime DATETIME NOT NULL CONSTRAINT DF_BTR_Invoice_CreateTime DEFAULT('3000-01-01'),
    LastUpdate DATETIME NOT NULL CONSTRAINT DF_BTR_Invoice_LastUpdate DEFAULT('3000-01-01'),
    UserId VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_Invoice_UserId DEFAULT(''),

    VoidDate DATETIME NOT NULL CONSTRAINT DF_BTR_Invoice_VoidDate DEFAULT('3000-01-01'),
    UserIdVoid VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_Invoice_UserIdVoid DEFAULT(''),

    
    CONSTRAINT PK_BTR_Invoice PRIMARY KEY CLUSTERED (InvoiceId)
)