CREATE TABLE BTR_Mutasi(
    MutasiId VARCHAR(13) NOT NULL CONSTRAINT PK_BTR_Mutasi_MutasiId DEFAULT(''), 
    MutasiDate DATETIME NOT NULL CONSTRAINT PK_BTR_Mutasi_MutasiDate DEFAULT('3000-01-01'), 
    JenisMutasi INT NOT NULL CONSTRAINT PK_BTR_Mutasi_JenisMutasi DEFAULT(0), 
    WarehouseId VARCHAR(3) NOT NULL CONSTRAINT PK_BTR_Mutasi_WarehouseId DEFAULT(''),
    Keterangan VARCHAR(128) NOT NULL CONSTRAINT PK_BTR_Mutasi_Keterangan DEFAULT(''), 
    NilaiSediaan DECIMAL(18,2) NOT NULL CONSTRAINT PK_BTR_Mutasi_NilaiSediaan DEFAULT(0),
    
    UserId VARCHAR(20) NOT NULL CONSTRAINT PK_BTR_Mutasi_UserId DEFAULT(''), 
    CreateTime DATETIME NOT NULL CONSTRAINT PK_BTR_Mutasi_CreateTime DEFAULT('3000-01-01'), 
    LastUpdate DATETIME NOT NULL CONSTRAINT PK_BTR_Mutasi_LastUpdate DEFAULT('3000-01-01'), 
    VoidDate DATETIME NOT NULL CONSTRAINT PK_BTR_Mutasi_VoidDate DEFAULT('3000-01-01'), 
    UserIdVoid VARCHAR(20) NOT NULL CONSTRAINT PK_BTR_Mutasi_UserIdVoid DEFAULT(''),
    
    CONSTRAINT PK_BTR_Mutasi PRIMARY KEY CLUSTERED(MutasiId)   
)