CREATE TABLE BTR_ReturJual(
	ReturJualId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_ReturJual_ReturJualId DEFAULT(''),
	ReturJualDate DATETIME NOT NULL CONSTRAINT DF_BTR_ReturJual_ReturJualDate DEFAULT('3000-01-01'),
	FakturId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_ReturJual_FakturId DEFAULT(''),
	FakturCode VARCHAR(11) NOT NULL CONSTRAINT DF_BTR_ReturJual_FakturCode DEFAULT(''),
	CustomerId VARCHAR(6) NOT NULL CONSTRAINT DF_BTR_ReturJual_CustomerId DEFAULT(''),
	SalesPersonId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_ReturJual_SalesPersonI DEFAULT(''),
	WarehouseId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_ReturJual_WarehouseId DEFAULT(''),
	UserId VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_ReturJual_UserId DEFAULT(''),
    Total DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJual_Total DEFAULT(0),
    DiscRp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJual_DiscRp DEFAULT(0),
    PpnRp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJual_PpnRp DEFAULT(0),
    GrandTotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJual_GrandTotal DEFAULT(0),

	CONSTRAINT PK_BTR_ReturJual PRIMARY KEY CLUSTERED (ReturJualId ASC)
)