CREATE TABLE [dbo].[BTR_ReturJualItem]
(
	ReturJualId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_ReturJualItem_ReturJualId DEFAULT (''),
	NoUrut INT NOT NULL CONSTRAINT DF_BTR_ReturJualItem_NoUrut DEFAULT (0),
    BrgId VARCHAR(6) NOT NULL CONSTRAINT DF_BTR_ReturJualItem_BrgId DEFAULT (''),
    BrgCode VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_ReturJualItem_BrgCode DEFAULT (''),
    
    QtyInputStr VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_ReturJualItem_QtyInputStr DEFAULT (''),
    QtyBesar INT NOT NULL CONSTRAINT DF_BTR_ReturJualItem_QtyBesar DEFAULT (0),
    SatBesar VARCHAR(7) NOT NULL CONSTRAINT DF_BTR_ReturJualItem_SatBesar DEFAULT (''),
    HrgSatBesar DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJualItem_HrgSatBesar DEFAULT (0),
    
    QtyKecil INT NOT NULL CONSTRAINT DF_BTR_ReturJualItem_QtyKecil DEFAULT (0),
    SatKecil VARCHAR(7) NOT NULL CONSTRAINT DF_BTR_ReturJualItem_SatKecil DEFAULT (''),
    HrgSatKecil DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJualItem_HrgSatKecil DEFAULT (0),
    
    Qty INT NOT NULL CONSTRAINT DF_BTR_ReturJualItem_QtySed DEFAULT (0),
    HrgSat DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJualItem_HrgSat DEFAULT (0),
    SubTotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJualItem_SubTotal DEFAULT (0),
    DiscRp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJualItem_DiscRp DEFAULT (0),
    PpnRp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJualItem_PpnRp DEFAULT (0),
    Total DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJualItem_Total DEFAULT (0),
    
    CONSTRAINT PK_BTR_ReturJualItem PRIMARY KEY CLUSTERED (ReturJualId,NoUrut)
)
