-- create table for RetyrJualItemQtyHrgModel
CREATE TABLE BTR_ReturJualItemQtyHrg(
	ReturJualId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_ReturJualQtyHrg_ReturJualId DEFAULT(''),
	ReturJualItemId VARCHAR(16) NOT NULL CONSTRAINT DF_BTR_ReturJualQtyHrg_ReturJualItemId DEFAULT(''),
	ReturJualItemQtyHrgId VARCHAR(16) NOT NULL CONSTRAINT DF_BTR_ReturJualQtyHrg_ReturJualItemQtyHrgId DEFAULT(''),
	NoUrut INT NOT NULL CONSTRAINT DF_BTR_ReturJualQtyHrg_NoUrut DEFAULT(0),
	Qty INT NOT NULL CONSTRAINT DF_BTR_ReturJualQtyHrg_Qty DEFAULT(0),
	HrgSat DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJualQtyHrg_HrgSat DEFAULT(0),
	SubTotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJualQtyHrg_SubTotal DEFAULT(0),
	DiscRp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJualQtyHrg_DiscRp DEFAULT(0),
	PpnRp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJualQtyHrg_PpnRp DEFAULT(0),
	Total DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJualQtyHrg_Total DEFAULT(0),

	CONSTRAINT PK_BTR_ReturJualQtyHrg PRIMARY KEY CLUSTERED(ReturJualItemId)
)


