CREATE TABLE [dbo].[BTR_Depo]
(
	DepoId VARCHAR(3) NOT NULL CONSTRAINT DF_BTR_Depo_DepoId DEFAULT(''),
	DepoName VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_Depo_DepoName DEFAULT(''),
	CONSTRAINT PK_BTR_Depo PRIMARY KEY CLUSTERED (DepoId)
)
GO
