CREATE TABLE [dbo].[BTR_Packing]
(
	PackingId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_Packing_PackingId DEFAULT(''),
	PackingDate DATETIME NOT NULL CONSTRAINT DF_BTR_Packing_PackingDate DEFAULT(''),
	DriverId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Packing_DriverId DEFAULT(''),
	Route VARCHAR(255) NOT NULL CONSTRAINT DF_BTR_Packing_Route DEFAULT(''),

	CONSTRAINT PK_BTR_Packing PRIMARY KEY CLUSTERED (PackingId)
)
