CREATE TABLE [dbo].[BTR_StokOp]
(
	StokOpId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_StokOp_StokOpId DEFAULT(''),
	StokOpDate DATETIME NOT NULL CONSTRAINT DF_BTR_StokOp_StokOpDate DEFAULT('3000-01-01'),
	PeriodeOp DATETIME NOT NULL CONSTRAINT DF_BTR_StokOp_PeriodeOp DEFAULT('3000-01-01'),
	BrgId VARCHAR(6) NOT NULL CONSTRAINT DF_BTR_StokOp_BrgId DEFAULT(''),
	WarehouseId VARCHAR(3) NOT NULL CONSTRAINT DF_BTR_StokOp_WarehouseId DEFAULT(''),
	
	QtyBesarAwal INT NOT NULL CONSTRAINT DF_BTR_StokOp_QtyBesarAwal DEFAULT(0),
	QtyKecilAwal INT NOT NULL CONSTRAINT DF_BTR_StokOp_QtyKecilAwal DEFAULT(0),
	QtyPcsAwal INT NOT NULL CONSTRAINT DF_BTR_StokOp_QtyPcsAwal     DEFAULT(0),
	
	QtyBesarOpname INT NOT NULL CONSTRAINT DF_BTR_StokOp_QtyBesarOpname DEFAULT(0),
	QtyKecilOpname INT NOT NULL CONSTRAINT DF_BTR_StokOp_QtyKecilOpname DEFAULT(0),
	QtyPcsOpname INT NOT NULL CONSTRAINT DF_BTR_StokOp_QtyPcsOpname DEFAULT(0),
	
	QtyBesarAdjust INT NOT NULL CONSTRAINT DF_BTR_StokOp_QtyBesarAdjust DEFAULT(0),
	QtyKecilAdjust INT NOT NULL CONSTRAINT DF_BTR_StokOp_QtyKecilAdjust DEFAULT(0),
	QtyPcsAdjust INT NOT NULL CONSTRAINT DF_BTR_StokOp_QtyPcsAdjust DEFAULT(0),

    QtyOpnameInputStr VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_StokOp_QtyOpnameInputStr DEFAULT(''),
	UserId VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_StokOp_UserId DEFAULT(''),

	CONSTRAINT PK_BTR_StokOp PRIMARY KEY CLUSTERED (StokOpId)
)
