-- create table for ReturJualModel
CREATE TABLE [dbo].[BTR_ReturJual](
	ReturJualId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_ReturJual_ReturJualId DEFAULT(''),
	ReturJualDate DATETIME NOT NULL CONSTRAINT DF_BTR_ReturJual_ReturJualDate DEFAULT(''),
	JenisRetur VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_ReturJual_JenisRetur DEFAULT(''),

	CustomerId VARCHAR(6) NOT NULL CONSTRAINT DF_BTR_ReturJual_CustomerId DEFAULT(''),
	WarehouseId VARCHAR(3) NOT NULL CONSTRAINT DF_BTR_ReturJual_WarehouseId DEFAULT(''),
    SalesPersonId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_ReturJual_SalesPersonId DEFAULT(''),
    DriverId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_ReturJual_DriverId DEFAULT(''),
	UserId VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_ReturJual_UserId DEFAULT(''),

	Total DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJual_Total DEFAULT(''),
	DiscRp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJual_DiscRp DEFAULT(''),
	PpnRp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJual_PpnRp DEFAULT(''),
	GrandTotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_ReturJual_GrandTotal DEFAULT(''),

    VoidDate DATETIME NOT NULL CONSTRAINT DF_BTR_ReturJual_VoidDate DEFAULT('3000-01-01'),
    UserIdVoid VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_ReturJual_UserIdVoid DEFAULT(''),
	
	CONSTRAINT [PK_BTR_ReturJual] PRIMARY KEY CLUSTERED  (ReturJualId)
)