CREATE TABLE BTR_Brg(
    BrgId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Brg_BrgId DEFAULT(''),
    BrgName VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_Brg_BrgName DEFAULT(''),
    
    CONSTRAINT PK_BTR_Brg PRIMARY KEY CLUSTERED (BrgId)
)