CREATE TABLE BTR_Stok(
    StokId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_Stok_StokId DEFAULT(''),
    StokControlId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_Stok_StokControlId DEFAULT(''),
    StokControlDate DATETIME NOT NULL CONSTRAINT DF_BTR_Stok_StokControlDate DEFAULT('3000-01-01'),
    BrgId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Stok_BrgId DEFAULT(''),
    WarehouseId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Stok_WarehouseId DEFAULT(''),
    QtyIn INT NOT NULL CONSTRAINT DF_BTR_Stok_QtyIn DEFAULT(0),
    Qty INT NOT NULL CONSTRAINT DF_BTR_Stok_Qty DEFAULT(0),
    NilaiPersediaan DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Stok_NilaiPersediaan DEFAULT(0),
    
    CONSTRAINT PK_BTR_Stok PRIMARY KEY CLUSTERED (StokId)
)
GO

CREATE INDEX IX_BTR_Stok_BrgId_WarehouseId
    ON BTR_Stok(BrgId, WarehouseId, Qty, StokId)
    WITH(FILLFACTOR=60)
GO