CREATE TABLE [dbo].[BTR_MutasiDisc]
(
	MutasiId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_MutasiDisc_MutasiId DEFAULT(''),
	MutasiItemId VARCHAR(16) NOT NULL CONSTRAINT DF_BTR_MutasiDisc_MutasiItemId DEFAULT(''),
	MutasiDiscId VARCHAR(19) NOT NULL CONSTRAINT DF_BTR_MutasiDisc_MutasiDiscId DEFAULT(''),
	NoUrut INT NOT NULL CONSTRAINT DF_BTR_MutasiDisc_NoUrut DEFAULT(0),
	BrgId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_MutasiDisc_BrgId DEFAULT(''),
	DiscProsen DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_MutasiDisc_DiscProsen DEFAULT(0),
	DiscRp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_MutasiDisc_DiscRp DEFAULT(0),

	CONSTRAINT PK_BTR_MutasiDisc PRIMARY KEY CLUSTERED (MutasiDiscId)	
)
GO

CREATE INDEX IX_BTR_MutasiDisc_MutasiId
	ON BTR_MutasiDisc (MutasiId, MutasiDiscId)
GO

