CREATE TABLE BTR_Faktur
(
    FakturId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_Faktur_FakturId DEFAULT(''),
    FakturDate DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_FakturDate DEFAULT('3000-01-01'),
    FakturCode VARCHAR(11) NOT NULL CONSTRAINT DF_BTR_Faktur_FakturCode DEFAULT(''),
    SalesPersonId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Faktur_SalesPersonId DEFAULT(''),
    CustomerId VARCHAR(6) NOT NULL CONSTRAINT DF_BTR_Faktur_CustomerId DEFAULT(''),
    HargaTypeId VARCHAR(2) NOT NULL CONSTRAINT DF_BTR_Faktur_HargaTypeId DEFAULT(''),
    WarehouseId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Faktur_WarehouseId DEFAULT(''),
    TglRencanaKirim DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_TglRencanaKirim DEFAULT('3000-01-01'),
    TermOfPayment INT NOT NULL CONSTRAINT DF_BTR_Faktur_TermOfPayment DEFAULT(0),
    DueDate DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_DueDate DEFAULT('3000-01-01'),

    Total DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_Total DEFAULT(0),
    Discount DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_Discount DEFAULT(0),
    Tax DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_Tax DEFAULT(0),
    GrandTotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_GrandTotal DEFAULT(0),
    UangMuka DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_UangMuka DEFAULT(0),
    KurangBayar DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_KurangBayar DEFAULT(0),
    NoFakturPajak VARCHAR(19) NOT NULL CONSTRAINT DF_BTR_Faktur_NoFakturPajak DEFAULT(''),

    CreateTime DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_CreateTime DEFAULT('3000-01-01'),
    LastUpdate DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_LastUpdate DEFAULT('3000-01-01'),
    UserId VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_Faktur_UserId DEFAULT(''),

    VoidDate DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_VoidDate DEFAULT('3000-01-01'),
    UserIdVoid VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_Faktur_UserIdVoid DEFAULT(''),
    
    CONSTRAINT PK_BTR_Faktur PRIMARY KEY CLUSTERED (FakturId)
)
GO

CREATE INDEX IX_BTR_Faktur_FakturDate
    ON BTR_Faktur(FakturDate, FakturId)
GO