CREATE TABLE [dbo].[BTR_AlokasiFp]
(
	AlokasiFpId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_AlokasiFp_AlokasiFpId DEFAULT(''),
	AlokasiFpDate DATETIME NOT NULL CONSTRAINT DF_BTR_AlokasiFp_AlokasiFpDate DEFAULT(''),
	NoAwal VARCHAR(19) NOT NULL CONSTRAINT DF_BTR_AlokasiFp_NoAwal DEFAULT(''),
	NoAkhir VARCHAR(19) NOT NULL CONSTRAINT DF_BTR_AlokasiFp_NoAkhir DEFAULT(''),
	Kapasitas INT NOT NULL CONSTRAINT DF_BTR_AlokasiFp_Kapasitas DEFAULT(0),
	Sisa INT NOT NULL CONSTRAINT DF_BTR_AlokasiFp_Sisa DEFAULT(0),

	CONSTRAINT PK_BTR_AlokasiFp PRIMARY KEY CLUSTERED(AlokasiFpId)
)
