CREATE TABLE [dbo].[BTR_OrderMap]
(
    OrderId VARCHAR(26) NOT NULL CONSTRAINT DF_BTR_OrderMap_OrderId DEFAULT(''),
    FakturId VARCHAR(15) NOT NULL CONSTRAINT DF_BTR_OrderMap_FakturId DEFAULT(''),
    FakturCode VARCHAR(10) NOT NULL CONSTRAINT DF_BTR_OrderMap_FakturCode DEFAULT(''),
    UserName VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_OrderMap_UserName DEFAULT(''),
    Timestamp DATETIME NOT NULL CONSTRAINT DF_BTR_OrderMap_Timestamp DEFAULT('3000-01-01')

    CONSTRAINT PK_BTR_OrderMap PRIMARY KEY CLUSTERED(OrderId)
)