CREATE TABLE BTR_Faktur
(
    FakturId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_Faktur_FakturId DEFAULT(''),
    FakturDate DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_FakturDate DEFAULT('3000-01-01'),
    SalesPersonId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Faktur_SalesPersonId DEFAULT(''),
    CustomerId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Faktur_CustomerId DEFAULT(''),
    WarehouseId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Faktur_WarehouseId DEFAULT(''),
    TglRencanaKirim DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_TglRencanaKirim DEFAULT('3000-01-01'),
    TermOfPayment VARCHAR(3) NOT NULL CONSTRAINT DF_BTR_Faktur_TermOfPayment DEFAULT(''),
    Total DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_Total DEFAULT(0),
    DiscountLain DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_DiscountLain DEFAULT(0),
    BiayaLain DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_BiayaLain DEFAULT(0),
    GrandTotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_GrandTotal DEFAULT(0),
    UangMuka DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_UangMuka DEFAULT(0),
    KurangBayar DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_KurangBayar DEFAULT(0),
    
    CreateTime DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_CreateTime DEFAULT('3000-01-01'),
    LastUpdate DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_LastUpdate DEFAULT('3000-01-01'),
    UserId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_Faktur_UserId DEFAULT(''),
    
    CONSTRAINT PK_BTR_Faktur PRIMARY KEY CLUSTERED (FakturId)
)
