CREATE TABLE BTR_Faktur
(
    FakturId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_Faktur_FakturId DEFAULT(''),
    FakturDate DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_FakturDate DEFAULT('3000-01-01'),
    FakturCode VARCHAR(11) NOT NULL CONSTRAINT DF_BTR_Faktur_FakturCode DEFAULT(''),
    FakturCodeOri VARCHAR(8) NOT NULL CONSTRAINT DF_BTR_Faktur_FakturCodeOri DEFAULT(''),
    SalesPersonId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Faktur_SalesPersonId DEFAULT(''),
    CustomerId VARCHAR(6) NOT NULL CONSTRAINT DF_BTR_Faktur_CustomerId DEFAULT(''),
    HargaTypeId VARCHAR(2) NOT NULL CONSTRAINT DF_BTR_Faktur_HargaTypeId DEFAULT(''),
    WarehouseId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Faktur_WarehouseId DEFAULT(''),
    TglRencanaKirim DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_TglRencanaKirim DEFAULT('3000-01-01'),
    DriverId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Faktur_DriverId DEFAULT(''),
    TermOfPayment INT NOT NULL CONSTRAINT DF_BTR_Faktur_TermOfPayment DEFAULT(0),
    DueDate DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_DueDate DEFAULT('3000-01-01'),

    Total DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_Total DEFAULT(0),
    Discount DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_Discount DEFAULT(0),
    Dpp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_Dpp DEFAULT(0),
    Tax DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_Tax DEFAULT(0),
    GrandTotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_GrandTotal DEFAULT(0),

    TotalKlaim DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_TotalKlaim DEFAULT(0),
    DiscountKlaim DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_DiscountKlaim DEFAULT(0),
    DppKlaim DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_DppKlaim DEFAULT(0),
    TaxKlaim DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_TaxKlaim DEFAULT(0),
    GrandTotalKlaim DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_GrandTotalKlaim DEFAULT(0),

    UangMuka DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_UangMuka DEFAULT(0),
    KurangBayar DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_Faktur_KurangBayar DEFAULT(0),
    NoFakturPajak VARCHAR(19) NOT NULL CONSTRAINT DF_BTR_Faktur_NoFakturPajak DEFAULT(''),
    FpKeluaranId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_Faktur_FpKeluaranId DEFAULT(''),

    CreateTime DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_CreateTime DEFAULT('3000-01-01'),
    LastUpdate DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_LastUpdate DEFAULT('3000-01-01'),
    UserId VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_Faktur_UserId DEFAULT(''),

    VoidDate DATETIME NOT NULL CONSTRAINT DF_BTR_Faktur_VoidDate DEFAULT('3000-01-01'),
    UserIdVoid VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_Faktur_UserIdVoid DEFAULT(''),
    
    Note VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_Faktur_Note DEFAULT(''),
    IsHasKlaim BIT NOT NULL CONSTRAINT DF_BTR_Faktur_IsHasKlaim DEFAULT(0)

    CONSTRAINT PK_BTR_Faktur PRIMARY KEY CLUSTERED (FakturId)
)
GO

CREATE INDEX IX_BTR_Faktur_FakturDate
    ON BTR_Faktur(FakturDate, FakturId)
GO

CREATE UNIQUE INDEX IX_BTR_Faktur_FakturCode
    ON BTR_Faktur (FakturCode)
    WHERE FakturCode <> ''
GO