CREATE TABLE [dbo].[BTR_RuteItem]
(
	RuteId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_RuteItem_RuteId DEFAULT (''),
	NoUrut INT NOT NULL CONSTRAINT DF_BTR_RuteItem_NoUrut DEFAULT (0),
	CustomerId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_RuteItem_CustomerId DEFAULT (''),

	CONSTRAINT PK_BTR_RuteItem PRIMARY KEY CLUSTERED (RuteId, NoUrut)
)
