CREATE TABLE [dbo].[BTR_HariRute]
(
	HariRuteId VARCHAR(3) NOT NULL CONSTRAINT DF_BTR_HariRute_HariRuteId DEFAULT(''),
	HariRuteName VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_HariRute_HariRuteName DEFAULT(''),
	ShortName VARCHAR(8) NOT NULL CONSTRAINT DF_BTR_HariRUte_ShortRuteName DEFAULT(''),

	CONSTRAINT PK_BTR_HariRute  PRIMARY KEY CLUSTERED  (HariRuteId)
)
