CREATE TABLE [dbo].[BTR_Rute]
(
	RuteId VARCHAR(5) NOT NULL CONSTRAINT DF_BTR_Rute_RuteId DEFAULT (''),
	RuteCode VARCHAR(10) NOT NULL CONSTRAINT DF_BTR_Rute_RuteCode DEFAULT (''),
	RuteName VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_Rute_RuteName DEFAULT (''),

	CONSTRAINT PK_BTR_Rute PRIMARY KEY CLUSTERED (RuteId)
)
