CREATE  TABLE BTR_FakturItem(
    FakturId VARCHAR(13) NOT NULL CONSTRAINT DF_BTR_FakturItem_FakturId DEFAULT(''),
    FakturItemId VARCHAR(16) NOT NULL CONSTRAINT DF_BTR_FakturItem_FakturItemId DEFAULT(''),
    NoUrut INT NOT NULL CONSTRAINT DF_BTR_FakturItem_ItemNo DEFAULT(''),
    
    BrgId VARCHAR(6) NOT NULL CONSTRAINT DF_BTR_FakturItem_BrgId DEFAULT(''),
    BrgCode VARCHAR(10) NOT NULL CONSTRAINT DF_BTR_FakturItem_BrgCode DEFAULT(''),
    StokHargaStr VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_Faktur_StokHargaStr DEFAULT(''),
    QtyInputStr VARCHAR(20) NOT NULL CONSTRAINT DF_BTR_Faktur_QtyInputStr DEFAULT(''),
    QtyDetilStr VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_Faktur_QtyDetilStr DEFAULT(''),
    HrgInputStr VARCHAR(30) NOT NULL CONSTRAINT DF_BTR_Faktur_HrgInputStr DEFAULT(''),

    QtyBesar INT NOT NULL CONSTRAINT DF_BTR_FakturItem_QtyBesar DEFAULT(0),
    SatBesar VARCHAR(10) NOT NULL CONSTRAINT DF_BTR_FakturItem_SatBesar DEFAULT(''),
    Conversion INT NOT NULL CONSTRAINT DF_BTR_FakturItem_Conversion DEFAULT(1),
    HrgSatBesar DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_FakturItem_HargaSatBesar DEFAULT(0),

    QtyKecil INT NOT NULL CONSTRAINT DF_BTR_FakturItem_QtyKecil DEFAULT(0),
    SatKecil VARCHAR(10) NOT NULL CONSTRAINT DF_BTR_FakturItem_SatKecil DEFAULT(''),
    HrgSatKecil DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_FakturItemHrgSatKecil DEFAULT(''),

    QtyJual INT NOT NULL CONSTRAINT DF_BTR_FakturItem_QtyJual DEFAULT(0),
    HrgSat DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_FakturItem_HargaSatuan DEFAULT(0),
    SubTotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_FakturItem_SubTotal DEFAULT(0),
    
    QtyBonus INT NOT NULL CONSTRAINT DF_BTR_FakturItem_QtyBonus DEFAULT(0),
    QtyPotStok INT NOT NULL CONSTRAINT DF_BTR_FakturItem_QtyPotStok DEFAULT(0),
    
    DiscInputStr VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_FakturItem_DiscInputStr DEFAULT(''),
    DiscDetilStr VARCHAR(50) NOT NULL CONSTRAINT DF_BTR_FakturItem_DiscDetilStr DEFAULT(''),
    DiscRp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_FakturItem_DiscRp DEFAULT(0),
    
    DppProsen DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_FakturItem_DppProsen DEFAULT(0),
    DppRp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_FakturItem_DppRp DEFAULT(0),
    PpnProsen DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_FakturItem_PpnProsen DEFAULT(0),
    PpnRp DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_FakturItem_PpnRp DEFAULT(0),
    Total DECIMAL(18,2) NOT NULL CONSTRAINT DF_BTR_FakturItem_Total DEFAULT(0),

    CONSTRAINT PK_BTR_FakturItem PRIMARY KEY CLUSTERED(FakturItemId)
)
GO

CREATE INDEX IX_BTR_Faktur_FakturId
    ON BTR_FakturItem (FakturId, FakturItemId)
GO

